spring:
  config:
    import: optional:file:.env[.properties]

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100

  data:
    web:
      pageable:
        default-page-size: 20

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 50MB

server:
  error:
    include-stacktrace: never

logging:
  level:
    root: info
    sql: debug
    org.springframework.security: trace
    org.hibernate.orm.jdbc.bind: trace
